databases:
  - name: heatseek-apidb
    plan: free
    databaseName: api
    user: api

services:
  - type: web
    plan: free
    name: heatseek-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heatseek-apidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
